version: '3'
services:
  eurekaserver1:
    image: raynspace/eureka-server:1.0.0
    ports:
      - "7900:8900"
    environment:

      - spring.profiles.active=test_ha_1
    networks:
      - webnet
  eurekaserver2:
    image: raynspace/eureka-server:1.0.0
    #hostname: eurekaserver2
    ports:
      - "7800:8900"
    environment:
      - spring.profiles.active=test_ha_2
    networks:
      - webnet
  commonapi:
    image: raynspace/common-api:1.0.0
#    deploy: 　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　
#      replicas: 2
#      resources:


#        limits:
#          cpus: "0.1"
#          memory: 10M
#        restart_policy:
#          condition: on-failure
    ports:
      - "8090:8090"
    depends_on:
      - eurekaserver1
      - eurekaserver2
    networks:
      - webnet
networks:
  webnet: