server:
  port: 8090

spring:
  application:
    name: common-api
#  boot:
#    admin:
#      context-path: /sba
#      client:
#        prefer-ip: true
#      url: http://localhost:8090

management:
  security:
    enabled: false # spring-boot 1.5.2之后严格执行安全策略，所以需要配置这个为false ,否则很多点监控不到

eureka:
  instance:
    hostname: API-SERVICE
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8900/eureka
#      defaultZone: http://localhost:7900/eureka,http://localhost:7800/eureka
#      defaultZone: http://eurekaserver1:8900/eureka,http://eurekaserver2:8900/eureka
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"
