server:
  port: 8082
spring:
  application:
    name: framework-common

management:
  security:
    enabled: false

eureka:
  instance:
    hostname: framework-common
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"

